- app/public/css/styles.css
- app/views/first_run/password.erb
- app/views/sessions/new.erb
- config/locales/en.yml
Functionality is unchanged (the user only sees the password field), but the invisible username field coerces Safari into prompting to save the password.
> Add invisible username fields to create and login

- docs/Heroku.md
When I created new app on Heroku and set APP_URL, I got a following error.
```
!    Usage: heroku config:set KEY1=VALUE1 [KEY2=VALUE2 ...]
!    Must specify KEY and VALUE to set.
```
`heroku apps:info` recently give me two urls, Git URL and Web URL.
ex.
Git URL:       https://git.heroku.com/TESTAPP-cedar-14.git
Web URL:       https://TESTAPP-cedar-14.herokuapp.com/
To set APP_URL I modified regexp to get only Web URL.
Is there more better way to do?
> Set APP_URL for Heroku

- app.json
Stringer depends on a PostgreSQL database, so enable the hobby-dev (free) version of the addon on one-click deploy.
Ref: #368
> Enable PostgreSQL addon on one-click deploy

- .travis.yml
- Gemfile.lock
Updates some dependencies which are required for ruby 2.2.0. I've tested all of them on ruby 2.0.0 and 2.1.5 to make sure they don't break on those rubies.
This will make https://github.com/swanson/stringer/issues/364 easier. :)
> Ruby 2.2 fixes

- app/controllers/feeds_controller.rb
Read the feed URL from params on request to `/feeds/new` and let it fill the feed URL field. This enables integration with the [RSS Subscription Extension][rss-subscription-ext] extension for Google Chrome and should allow integration with similar extensions, for Google Chrome or other browsers.
[rss-subscription-ext]: https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd
> Fill feed URL field from params

- README.md
- app/utils/sample_story.rb
- app/views/tutorial.erb
3 changes, in decreasing order of importance:
* Heroku automatically sends you to the HTTPS version of the app when you install with Heroku Button.
Then, Firefox (since [version 23](https://developer.mozilla.org/en-US/docs/Security/MixedContent/How_to_fix_website_with_mixed_content)) blocks the download of Reenie Beanie, and apparently replaces it with Comic Sans MS?!
* The changes in README.md are mostly irrelevant because of https://help.github.com/articles/why-do-my-images-have-strange-urls/, but it's good practice, in case it ends up getting rendered somewhere that isn't GitHub.
* I'm not sure if the Placekitten one is even viewable from a browser -- I didn't bother checking. The HTTPS version of the resource does load, however, so it probably won't break anything.
> use TLS for external resources

- app.rb
- app/controllers/sessions_controller.rb
- spec/controllers/sessions_controller_spec.rb
When going to an URL that needs authentication (like `/archive/` or `/feed/:id`) we currently get redirected to the login page and then to the feed index. This redirects to the page we initially tried to access after login.
> Redirect to the previous page after login

- app.json
> Heroku serves a wildcard *.herokuapp.com certificate, so for most people, HSTS
> should be enabled.
<https://github.com/swanson/stringer/issues/382#issue-100622734>
> Enforce SSL by default when using the Heroku button

- app/repositories/story_repository.rb
- spec/repositories/story_repository_spec.rb
Before, normalize_url would completely bork relative urls.
In the example used in the spec the result would be
`https:/progrium/dokku/releases/tag/v0.4.4` which is of course
completely wrong.
> Fix handling of relative entry urls

- docs/Heroku.md
The `heroku apps:info --shell` command outputs the app's URL in an attribute named `web-url`, not `web_url` (with a hyphen, not an underscore).
> Fix command that sets APP_URL in Heroku.md

- .rubocop_todo.yml
- db/migrate/20140421224454_fix_invalid_unicode.rb
- db/migrate/20141102103617_fix_invalid_titles_with_unicode_line_endings.rb
* Fix Performance/StringReplacement
> ### delete([other_str]+) -> new_str
>
> Returns a copy of *str* with all characters in the intersection of its
> arguments deleted. Uses the same rules for building the set of characters as
> `String#count`.
See <http://ruby-doc.org/core-2.0.0/String.html#method-i-delete>.
> Fix RuboCop performance offences

- .rubocop.yml
- .rubocop_todo.yml
- app/commands/feeds/export_to_opml.rb
- app/commands/feeds/find_new_stories.rb
- app/fever_api/response.rb
- app/fever_api/write_mark_feed.rb
- app/fever_api/write_mark_group.rb
- app/fever_api/write_mark_item.rb
- app/helpers/authentication_helpers.rb
- app/helpers/url_helpers.rb
- app/repositories/story_repository.rb
- app/tasks/fetch_feed.rb
- app/utils/opml_parser.rb
- app/utils/sample_story.rb
- db/migrate/20130425222157_add_delayed_job.rb
- spec/factories/story_factory.rb
- spec/helpers/authentications_helper_spec.rb
- spec/helpers/url_helers_spec.rb
- spec/repositories/story_repository_spec.rb
* Fix Metrics/AbcSize
...through some light refactorings.
* Fix Metrics/CyclomaticComplexity
...through a small refactoring of `Sinatra::AuthenticationHelpers#needs_authentication?`.
* Set Metrics/LineLength maximum to 120 characters
Matt and I agreed that 120 characters is a sensible maximum line length for modern editors, see
<https://github.com/swanson/stringer/pull/395#issuecomment-166069080>.
Also set the `MaxLineLength` option for two other cops, since they're related.
Joins lines in the Fever API files to fix warnings from `Style/IfUnlessModifier`.
* Lower Metrics/MethodLength maximum to 15 lines
Despite my best efforts, I find it hard to keep all methods below or at the default maximum length of 10 lines. 15 lines is a somewhat arbitrary compromise that's subject to future …
> Fix RuboCop metrics offences

- app/controllers/feeds_controller.rb
- app/public/css/styles.css
- app/repositories/feed_repository.rb
- app/views/feeds/edit.erb
- config/locales/en.yml
- spec/controllers/feeds_controller_spec.rb
I've been using groups for quite a while. While this is a hidden feature it would be handy that feeds could be linked using the interface. The dropdown will only be shown when there are any groups so that people not using the feature don't get confused about it.
I might also look into more group management later on, but I rarely use the web interface so it's not really a priority for me right now. (and I've got a lot of other stuff on my plate)
The only think that needs to be fixed is the design of the dropdown. I guess stringer is a custom theme? Would any of you mind to help me fix it? I'll try to fix it myself but it might take a few days/weeks.
> Adds group_id to Feeds#edit

- docs/OpenShift.md
`rubocop` now has a `require` so we need to change it to the old syntax for openshift.
> Fix outdated documentation

- .travis.yml
- Gemfile
1. In a `Gemfile.local`
1. From the environment `$RUBY_VERSION` (not sure how this behaves on JRuby)
1. From the `.ruby-version` file
1. Defaults to `2.0.0`
Ref:
- https://github.com/swanson/stringer/issues/364
- https://github.com/swanson/stringer/pull/408
> RFC: Lots of ways to configure the Ruby version

- docs/Heroku.md
> WARNING: `heroku addons:add` has been deprecated. Please use `heroku addons:create` instead.
> Update Heroku.md (heroku addons:create)

- Rakefile
- app.json
- app/tasks/fetch_feeds.rb
- config/unicorn.rb
This PR intends to make the Delayed Job processing more robust.
In my tests, while running Stringer in a Docker container, there was an issue on passing the `Feed` data to the Delayed Job.
The whole object was serialized by the application (`FetchFeeds` class) and deserialized by the Delayed Job.
That's not a good practice and can cause several issues, as you can see in https://github.com/collectiveidea/delayed_job_active_record/issues/101
To solve this, instead of passing the whole `Feed` object to the Delayed Job, only its `id` attribute is sent. Then, the `Feed` is get from the database and its content is fetched normally.
Plus, the `@pool` object (a pool of threads) was also serialized and sent, causing issues.
If no `pool` is passed to the job, it should be instantiated from inside …
> Improving how data is passed to Delayed Job

- Rakefile
Fixes the following error introduced in 81a60ac44197a021aa8a7b9876acb3b6642436d8.
rake aborted!
NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails
/home/koronen/.gem/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:55:in `db_dir'
/home/koronen/.gem/ruby/2.3.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/rake.rb:112:in `db_dir'
We set `db_dir` explicitly to prevent `ActiveRecord` from using a default value that references `Rails.application.config`.
Ref: <https://github.com/swanson/stringer/pull/428>
Fixes #436 and fixes #437.
> Explicitly set `db_dir` in Rakefile

- app.rb
I often times add new feeds to Stringer via a Chrome extension that redirects to `<stringer>/feeds/new?feed_url=something`. I noticed that when I have to login I would always get redirected to `feeds/new` so Stringer was dropping the querystring.
This PR fixes that by settings `session[:redirect_to]` to `request.fullpath`, which does include the querystring.
> Redirect to request.fullpath when request needs authentication

- app/repositories/story_repository.rb
If you use a service that turns newsletters into RSS feeds, you will
receive entries without an URL. Saving those entries would fail when
normalizing the URL.
> Allow entries without an URL

- app/fever_api/response.rb
- fever_api.rb
- spec/fever_api_spec.rb
I am the developer of Unread, an RSS reader for iOS:
https://www.goldenhillsoftware.com/unread/
I recently implemented Fever URL validation. Unread performs this validation before asking for the customer's credentials. This validation attempts to confirm that the Fever URL is correct by issuing a request to the Fever API without an API key and verifying that the API returns the following JSON:
{ "api_version": 3, "auth": 0 }
This works with Fever, but it is not working with Stringer because Stringer responds with a 403 and no response body when the request does not contain the correct API key. This pull request makes Stringer consistent with Fever in this regard.
> Make Handling of Missing or Incorrect Api Key Consistent With Fever Api

- docker/start.sh
- docs/docker.md
This PR updates the Docker docs to use the prebuilt image from Docker hub that was setup in #458.
I've also added a check to the Docker start script that will warn and abort when the image is started without specifying a `DATABASE_URL`. This to prevent people trying to run the image without any env vars (`docker run -it mdswanson/stringer`) are greeted with a big stacktrace.
> Update Docker docs to use image on Docker Hub

- docker-compose.yml
- docs/docker.md
If you're lazy like me, you try to automate your life. I've created this docker-compose example to quickly start up a Stringer instance and have all available options easily configured in one file, as opposed to running a containers manually using messy docker commands.
> Add docker-compose example and update docs

- app.rb
I found no place where the current default value of SECRET_TOKEN is used. So I propose to make it random by default using `SecureRandom.hex(32)`
> Make SECRET_TOKEN random by default

- .dockerignore
This avoids having the complete git history in the Docker image.
> Adds a dockerignore file

- app/repositories/story_repository.rb
Follwing the [spec](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt) for RSS, if the title property isn't present for a story, we should display the description, which is the [summary in feedjira](https://github.com/feedjira/feedjira/blob/d0a28c3ba6437d70e4ca886ae5c05287bf1b6821/lib/feedjira/parser/itunes_rss_item.rb#L13).
> Use summary when there isn't a title

- app/helpers/url_helpers.rb
The link field of this [feed](https://www.qdaily.com/feed.xml) contains whitespace, got this error:
`bad URI(is not URI?):   (URI::InvalidURIError)`
Strip the url before parsing it solve the problem.
> Strip url before parse it

- app/repositories/story_repository.rb
- spec/repositories/story_repository_spec.rb
- spec/spec_helper.rb
[this commit](https://github.com/swanson/stringer/commit/b4ae4c1d43c9f0bd597e76dcb3324ac6f89e8359) made the whole process fail when both url and enclosure_url do not exist. The reason is that `entry.enclosure_url.present?` throws an error, since the method doesn't exist at all
There's actually a much larger issue here, which is the error being silently hidden in `FetchFeed`, which just rescues every exception and flags the feed as red. This makes it very hard to debug errors
However I just fixed this one issue. I hope after re-deploying, my feeds will start working again, otherwise I'll have to get back at it
> Prevents crash when both url and enclosure_url dont exist

- app/repositories/story_repository.rb
- spec/repositories/story_repository_spec.rb
Parsing was failing if an entry had no defined URL. The parser was assuming it existed, and using it to expand all relative URLs
While it probably always exists for any well-made RSS feed, it won't be true if we're using something like [Kill The Newsletter](https://www.kill-the-newsletter.com/) to convert emails to RSS
> Fixes entry parse if there is no URL

- Gemfile.lock
As reported by `bundler-audit`:
> Name: loofah
> Version: 2.1.1
> Advisory: CVE-2018-8048
> Criticality: Unknown
> URL: https://github.com/flavorjones/loofah/issues/144
> Title: Loofah XSS Vulnerability
> Solution: upgrade to >= 2.2.1
Ref: <https://github.com/flavorjones/loofah/blob/v2.2.1/CHANGELOG.md#221--2018-03-19>
> Bump loofah to address CVE-2018-8048

- Gemfile.lock
As reported by `bundler-audit`:
> Name: nokogiri
> Version: 1.8.1
> Advisory: CVE-2017-15412
> Criticality: Unknown
> URL: https://github.com/sparklemotion/nokogiri/issues/1714
> Title: Nokogiri gem, via libxml, is affected by DoS vulnerabilities
> Solution: upgrade to >= 1.8.2
> Bump nokogiri to address CVE-2017-15412

- config/unicorn.rb
In this change I'm upgrading unicorn in order to get the call back
`after_worker_exit`. I need this in development to kill ghost workers
that are pilling up on my computer every time I restart the app.
> Upgrade Unicorn

- Gemfile
- Gemfile.lock
NoMethodError: undefined method `after_worker_exit' for
#<Unicorn::Configurator:0x005580f92c7480>
Did you mean?  after_fork
./config/unicorn.rb:25:in `reload'
This was probably meant to be a part of d73a7d7381f5bb1ece51819db41caa05a0831cbf (#475).
Fixes #483.
Ref: <https://bogomips.org/unicorn/NEWS.html#label-unicorn+5.3.0+-2F+2017-04-01+08-3A03+UTC>
> Bugfix: bump unicorn for after_worker_exit feature

- README.md
What happened to my badge? 
To avoid broken 404 images, all badges pointing to Gemnasium.com will be a placeholder, inviting you to migrate to GitLab (and pointing to this page).
https://docs.gitlab.com/ee/user/project/import/gemnasium.html
> Gemnasium is migratet to Gitlab and closed

- app/commands/feeds/add_new_feed.rb
- app/repositories/story_repository.rb
- app/utils/content_sanitizer.rb
- spec/commands/feeds/add_new_feed_spec.rb
- spec/repositories/story_repository_spec.rb
- spec/utils/content_sanitizer_spec.rb
Attempt to fix a recently reported XSS vulnerability.
We reuse the same sanitization strategy as for _story_ titles.
Also add a `StoryRepository` test for title-based XSS for good measure.
Fixes #490.
> Sanitize feed titles

- docs/Heroku.md
* `web-url` in the `heroku apps:info` output is now `web_url`
* Command was returning an empty string and setting that as the value of `APP_URL`
> Update command for setting APP_URL on Heroku

- docs/VPS.md
It looks like the [docs](../blob/master/docs/VPS.md#install-ruby-for-your-stringer-user) are referencing an older version of Ruby for its install that the build scripts are not using any more, just a minor correction. Thanks! :+1:
PS.: Also had to install `nodejs` - would this be something to add to the list of dependencies that are being installed at the top of the installation guide?
> Docs: Bring Version-Number for Localized Ruby Up to Date

- app/public/manifest.json
- app/views/layout.erb
- by adding the meta headers and manifest, if you add the website on mobile to you home screen, the browser chrome will dissappear and more screen space will be available for the reader
> Add web manifest to enable native app feel on mobile

- app/models/feed.rb
- spec/models/feed_spec.rb
This fixes an issue with `Feed#status_bubble` where it would *never*
return `:yellow`. `Feed#status` comes back as a string, so `status ==
:red` would always be falsey. This updates it to instead do a string
comparison.
> Add feed specs, fix status bug

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- spec/support/coverage.rb
It looks like Coveralls was disabled back in c84d7b8, but it seems to
have been unrelated to the code changes. This reenables it on CI, and
uses just `SimpleCov` in local development.
> Specs: restore coverage

- Gemfile
- Gemfile.lock
- app/models/application_record.rb
- app/models/feed.rb
- app/models/group.rb
- app/models/story.rb
- app/models/user.rb
- db/migrate/20130409010818_create_feeds.rb
- db/migrate/20130409010826_create_stories.rb
- db/migrate/20130412185253_add_new_fields_to_stories.rb
- db/migrate/20130418221144_add_user_model.rb
- db/migrate/20130423001740_drop_email_from_user.rb
- db/migrate/20130423180446_remove_author_from_stories.rb
- db/migrate/20130425211008_add_setup_complete_to_user.rb
- db/migrate/20130425222157_add_delayed_job.rb
- db/migrate/20130429232127_add_status_to_feeds.rb
- db/migrate/20130504005816_text_url.rb
- db/migrate/20130504022615_change_story_permalink_column.rb
- db/migrate/20130509131045_add_unique_constraints.rb
- db/migrate/20130513025939_add_keep_unread_to_stories.rb
- db/migrate/20130513044029_add_is_starred_status_for_stories.rb
- db/migrate/20130522014405_add_api_key_to_user.rb
- db/migrate/20130730120312_add_entry_id_to_stories.rb
- db/migrate/20130805113712_update_stories_unique_constraints.rb
- db/migrate/20130821020313_update_nil_entry_ids.rb
- db/migrate/20130905204142_use_text_datatype_for_title_and_entry_id.rb
- db/migrate/20140413100725_add_groups_table_and_foreign_keys_to_feeds.rb
- db/migrate/20140421224454_fix_invalid_unicode.rb
- db/migrate/20141102103617_fix_invalid_titles_with_unicode_line_endings.rb
- spec/support/active_record.rb
Followed the instructions at https://www.fastruby.io/blog/rails/upgrades/upgrade-rails-from-4-2-to-5-0.html to migrate to the newer version. Then fixed the `pec/support/active_record.rb` calls to work with the new API.
> Update to activerecord 5

- spec/factories.rb
- spec/factories/stories.rb
- spec/repositories/story_repository_spec.rb
- spec/spec_helper.rb
Also adjust the way that factories are required and introduce a
`next_id` helper. There are still some untested methods in
StoryRepository which I will continue to work on in followups.
> Specs: add specs for StoryRepository

- app/tasks/change_password.rb
- spec/tasks/change_password_spec.rb
This makes it so that we can pass input and output to ChangePassword in
order to test against them, and prevent them from outputting in the
tests.
> refactor specs for ChangePassword

- app/repositories/group_repository.rb
ActiveRecord no longer wants us to pass SQL fragments to `order`. This
instead makes use of the underlying framework Arel to generate the
query.
> fix ActiveRecord deprecation warning

- app/tasks/fetch_feeds.rb
- spec/factories/feeds.rb
- spec/tasks/fetch_feeds_spec.rb
This is super janky, grabbing the instance variable out of the instance,
but there doesn't seem to be a great way to test for the underlying
issue, which is that in some cases jobs don't work when passing the
entire record. I thought also about inspecting the job more closely, but
wasn't able to think of a great solution there, either. I'd like to
refactor this class some down the road to not try to juggle both
`@feeds_ids` and `@feeds` variables.
> Specs: add tests for FetchFeeds

- app/repositories/feed_repository.rb
- spec/repositories/feed_repository_spec.rb
* Add tests for `.fetch_by_ids`, `.delete`, `.list`, and `.in_group`
* Rearrange test file to mirror ordering of class
* Fix deprecation warning for `lower(name)`
* Refactor `in_group` query to use AR syntax
> Specs: add test coverage for FeedRepository

- spec/tasks/fetch_feed_spec.rb
The test wasn't actually executing the method under test, so it wasn't
verifying anything.
> Specs: actually execute code in fetch_feed_spec

- Gemfile
- Gemfile.lock
- db/schema.rb
- spec/models/story_spec.rb
I needed to update the format of the json being returned in the tests.
I'm not sure if it actually ends up changing the result when the dates
are converted to JSON strings, but it doesn't look like anything client
or server relies particularly on the format, so we should be fine.
Also updates the formatting in `schema.rb` by running `rake db:migrate`.
All of the changes look to be cosmetic.
> Deps: upgrade ActiveRecord to 6.1

- Gemfile
- Gemfile.lock
The [coveralls gem][gem] hasn't been updated in more than a year. The
[reborn][reborn] is a more up to date version that doesn't lock us down
on an older version of SimpleCov. We may want to consider removing
Coveralls entirely and just using the CI coverage, perhaps also keeping
the artifacts for easy reference.
[gem]: https://github.com/lemurheavy/coveralls-ruby
[reborn]: https://github.com/tagliala/coveralls-ruby-reborn
> Deps: switch to coveralls_reborn

- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
- Procfile
- config/puma.rb
- docker/supervisord.conf
- spec/spec_helper.rb
**What**
This switches the server we use from Unicorn to Puma
**Why**
* Puma is the blessed option [on Heroku][heroku].
* It [works with Capybara][capybara] out of the box.
* Ruby 3 [removes `webrick`][ruby3] from the core libraries, so we would
need to add it as a dependency for Capybara when upgrading. Might as
well consolidate on a single server.
**Notes**
I also moved `pg` out of the `production` group.
[heroku]: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#recommended-default-puma-process-and-thread-configuration
[capybara]: https://github.com/teamcapybara/capybara#drivers
[ruby3]: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
> Deps: switch from Unicorn to Puma

- Dockerfile
- README.md
- docker-compose.yml
Not sure, but I believe this will fix issues with HTTPS.
I also removed the deprecated `--deployment` flag when running `bundle
install`.
> Docker: upgrade Ruby version

- app/commands/stories/mark_as_read.rb
- app/commands/stories/mark_as_starred.rb
- app/commands/stories/mark_as_unread.rb
- app/commands/stories/mark_as_unstarred.rb
- spec/commands/stories/mark_as_read_spec.rb
- spec/commands/stories/mark_as_starred_spec.rb
- spec/commands/stories/mark_as_unread_spec.rb
- spec/commands/stories/mark_as_unstarred_spec.rb
This will replace the method `update_attributes` that was removed in ActiveRecord 6.1. 
Fixes #612
> Replacing removed update_attributes method

- config.ru
This adds `activesupport` as a dependency and requires
`active_support/all`. This should (hopefully) fix [this issue][is] where
an error is thrown when loading `Delayed::Job`.
[is]: https://github.com/stringer-rss/stringer/issues/644
> Errors: add activesupport dependency

- README.md
- app.json
- app.rb
- app/views/partials/_footer.erb
- docs/Heroku.md
- docs/OpenShift.md
- docs/VPS.md
- docs/docker.md
- spec/controllers/stories_controller_spec.rb
- spec/repositories/story_repository_spec.rb
Update GitHub links to point to `stringer-rss/stringer` and rename
`master` to `main`.
> update links and branch names

- README.md
For some reason it doesn't work without the `template` param for me.
Maybe I'm using a privacy extension that strips out the `referer`.
Explicitly passing the `template` will provide a more reliable
experience, even if it's a little less flexible, as forks will no longer
be able to be deployed as easily.
> update deploy button link

- .rubocop_todo.yml
- app/assets/stylesheets/application.css
- app/repositories/story_repository.rb
- app/views/js/templates/_story.js.erb
- db/migrate/20221206231914_add_enclosure_url_to_stories.rb
- db/schema.rb
- spec/javascript/spec/views/story_view_spec.js
- spec/models/story_spec.rb
- spec/repositories/story_repository_spec.rb
Many podcast and other media feeds have both a `url` and an
`enclosure_url`. For example, [the Welcome to Nightvale feed][wn]. In
these cases, there's a good chance the user might want to get straight
to the enclosure rather than being directed to another site to listen to
the track. This allows us to directly download the enclosure rather than
having to hunt it down somewhere else.
[wn]: http://feeds.nightvalepresents.com/welcometonightvalepodcast
> Add download link when story has enclosure

- .tool-versions
This file allows us to use tools like [`asdf`][asdf] to manage a wide
variety of application dependencies.
[asdf]: https://github.com/asdf-vm/asdf
> Deps: add a `.tool-versions` file

- .tool-versions
- Gemfile.lock
This updates our bundler version to match the latest version [currently
supported by Heroku][he].
[he]: https://devcenter.heroku.com/articles/ruby-support#libraries
> Deps: update bundler version

- app/assets/stylesheets/application.css
- app/views/js/templates/_story.js.erb
It's kind of a pain to hunt down the download link all the way at the
bottom, especially in cases where the body is longer.
> Move enclosure download link to the heading

- app.rb
This sets `Time.zone` inside `app.rb`. Currently it isn't set, which
causes `delayed_job_active_record` to [go down a deprecated path][dj].
`ActiveRecord#default_timezone` is deprecated and will be removed in
Rails 7.1, so setting the timezone avoids this issue and punts the
problem of an outdated queueing system down the road.
[dj]: https://github.com/collectiveidea/delayed_job_active_record/blob/d65b0f9900f5b0c78c341c7c0209c2d138d64ec5/lib/delayed/backend/active_record.rb#L175
> Set timezone in app.rb

- spec/spec_helper.rb
I had to add a monkey patch for `Rack::Test` as they don't seem to have
a good way to enable SSL by default otherwise.
> Security: enforce SSL in tests

- app.rb
This got lost in a recent change.
> Put SSL configuration back

- app/models/migration_status.rb
- spec/models/migration_status_spec.rb
The mocking hid the fact that the migration methods were no longer
available, so I updated the tests to use the actual classes.
`ActiveRecord::Base.connection.migration_context.open` always returns a
new instance, so for now we continue passing it down in order to avoid
needing to use `allow_any_instance_of`.
> fix debug page

- .rubocop_todo.yml
- app.rb
- spec/app_spec.rb
Now that we're loading `ActionController` it's also loading
`ActionDispatch`, causing the second case in [this line][tl] to raise an
error. For now we'll stub out `Rails` to prevent it.
[tl]: https://github.com/collectiveidea/delayed_job/blob/5ac5adea8d18325d0470eeebfa81227b1f5961e3/lib/delayed/worker.rb#L119
> Rails: fix issue with Delayed::Job

- app/commands/stories/mark_group_as_read.rb
It shouldn't be possible to get this far unless `group_id` is greater
than 0.
> Coverage: remove unused condition from MarkGroupAsRead

- app/commands/feeds/import_from_opml.rb
- spec/commands/feeds/import_from_opml_spec.rb
- spec/support/coverage.rb
- spec/support/files/subscriptions.xml
Based on the implementation of `OpmlParser` it doesn't look like there's
any way to hit this guard clause.
> Coverage: remove unused clause in importer

- .rubocop_todo.yml
- app/commands/feeds/add_new_feed.rb
- app/controllers/feeds_controller.rb
- spec/commands/feeds/add_new_feed_spec.rb
Use the URL in its place.
Fixes #744.
> Fix: handle feeds that are missing a title

- .rubocop.yml
- .rubocop_todo.yml
As much as I might prefer consistency, this one seems hard to enforce
safely.
> RuboCop: disable StringHashKeys cop

- .rubocop_todo.yml
- spec/controllers/stories_controller_spec.rb
The latter example wasn't actually testing anything, as the `have_tag`
matcher ignores the `class:` option. It's effectively only looking for
`li`. There description can't really be tested via controller tests, as
the stories are rendered via backbone.
> RuboCop: clean up specs for StoriesController

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- spec/support/webmock.rb
Prevent network connections. It's really easily to accidentally invoke
the `FeedDiscovery` class, which hits the network, so this will make
sure we don't forget.
> Specs: set up Webmock

- app/commands/users/change_user_password.rb
- app/commands/users/create_user.rb
- app/models/user.rb
- app/utils/api_key.rb
- spec/commands/users/change_user_password_spec.rb
MD5 isn't a stellar option for secure hashing, so you may want to
regenerate your api key after this change. We can instead use
`has_secure_token` to generate a random token rather than hashing based
on the password.
> Rails: switch api_key to has_secure_token

- docs/docker.md
Fix a small typo (`foler` to `folder`).
> Fix typo in docker compose documentation

- app/fever_api/authentication.rb
- spec/fever_api/authentication_spec.rb
- spec/fever_api_spec.rb
Per [the docs][do], `last_refreshed_on_time` is the most recently
refreshed feed timestamp. I default it to 0 when there are no feeds. I
considered using `nil`, but 0 seemed like it might be more compatible
with clients that don't handle the "no feeds" case gracefully.
[do]: https://github.com/dasmurphy/tinytinyrss-fever-plugin/blob/c4c866021560d9480d50b4258ee31bb50b80fbbc/fever-api.md#authentication
> Fever: use last feed update for timestamp

- config/routes.rb
Reeder app assumes that the path ends on a `/`, e.g. `http://www.example.com/fever/`. It always adds that `/`.
> Fixed routing for reeder app

- app/utils/sample_story.rb
When I added `enclosure_url`, it [broke the sample stories page][br] as
it uses custom structs rather than story instances. This adds
`enclosure_url` to the sample structs as well.
[br]: https://github.com/stringer-rss/stringer/issues/853
> UI: fix tutorial page rendering

- app/assets/stylesheets/application.css
- app/views/feeds/_feed.html.erb
There is [some layout overlap][ol] depending on the font size, so this
gives the wording dynamic spacing.
[ol]: https://github.com/stringer-rss/stringer/issues/853
> UI: adjust feeds page to use flex

- Gemfile
- Gemfile.lock
- spec/models/story_spec.rb
- spec/spec_helper.rb
* `factory_bot_rails` provides Rails generators which we don't need, and
not much else. We can rely on `factory_bot` instead.
* `shotgun` is used for reloading the server on file changes, which
Rails provides out of the box.
* `faker` can result in flaky tests, so we can use deterministic data in
our tests instead.
> Rails: clean up some gems

- app/views/passwords/new.html.erb
- spec/system/account_setup_spec.rb
Fix the Confirm label to be properly associated with the input.
> Capybara: add system spec for account setup

- app/controllers/application_controller.rb
- app/controllers/debug_controller.rb
- app/controllers/exports_controller.rb
- app/controllers/feeds_controller.rb
- app/controllers/fever_controller.rb
- app/controllers/imports_controller.rb
- app/controllers/passwords_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/stories_controller.rb
- app/controllers/tutorials_controller.rb
- app/models/story.rb
- app/utils/authorization.rb
- spec/javascript/test_controller.rb
- spec/requests/feeds_controller_spec.rb
- spec/requests/stories_controller_spec.rb
- spec/utils/authorization_spec.rb
This will help to ensure we don't expose the wrong data to different
users by raising an error when we forget to authorize an endpoint.
> MultiUsers: introduce Authorization class

- app/controllers/fever_controller.rb
Because we are encrypting the api key, it looks it up via the encrypted
hash, preventing timing attacks.
> MultiUsers: lookup fever user via api key

- app/commands/users/create_user.rb
- db/migrate/20230223231930_add_username_to_users.rb
The current instructions say to use "stringer" as the username for Fever
clients, so we should default the username to match.
> Fever: make stringer the default user

- app/assets/stylesheets/application.css
- app/controllers/profiles_controller.rb
- app/models/user.rb
- app/views/profiles/edit.html.erb
- config/locales/en.yml
- db/migrate/20230301024452_encrypt_api_key.rb
- spec/models/user_spec.rb
- spec/requests/profiles_controller_spec.rb
- spec/support/matchers.rb
- spec/system/profile_spec.rb
The fever spec requires this format, so this restores logic previously
removed.
> Fever: generate API key based on username/password

- app/tasks/fetch_feed.rb
- spec/tasks/fetch_feed_spec.rb
This no longer applies, as Feedjira no longer accepts the
`:if_modified_since` option. We removed the options when we upgraded to
Feedjira 2.x.
> Fetching: remove 304 logic

- app/commands/fever_api.rb
- app/commands/fever_api/response.rb
Depending on the test order, it might not find `API_VERSION`.
> RuboCop: fix module nesting 

- config/database.yml
- config/puma.rb
GoodJob is raising errors for lack of db connections and we're getting
memory warnings from Heroku.
> DB: adjust process numbers

- config.ru
This was needed due to an issue with Delayed::Job.
> Jobs: remove remaining reporting require

- config/initializers/good_job.rb
It turns out we generate *a lot* of jobs, so it can fill up a hobby
database on Heroku in less than a day.
> Jobs: don't preserve job records

- db/migrate/20130522014405_add_api_key_to_user.rb
- db/migrate/20230223045525_add_null_false_to_associations.rb
- db/migrate/20230223231930_add_username_to_users.rb
- db/migrate/20230313034938_add_admin_to_users.rb
**What**
This makes a couple of updates to the migrations based on [this
conversation][is]:
* Rename `Api` -> `API`. This is expected by Rails inflections.
* Add conditional checks to migrations that look for a user. If a person
hasn't set up an account yet, the migrations should still run
gracefully.
[is]: https://github.com/stringer-rss/stringer/issues/1046
> repair migrations

- Dockerfile
The download of `supercronic` in the Dockerfile hardcodes `amd64` as the architecture, but we can make it flexible to allow for multiarch builds.
For this purpose I added all three of the SHA1SUMs and just select the "correct" one to use based on the `ARCH` build argument (which has a default of `amd64`).
This built successfully for me with the command:
```
docker build -t stringer-arch-test --build-arg ARCH=arm64 .
```
(as well as `arm` and `amd64`)
I changed the shell that executes the Dockerfile to bash to take advantage of the `${!ENV_VAR_CONTAINING_OTHER_ENV_VAR_NAME}` construction - the `SUPERCRONIC_SHA1SUM` arg contains one of `SUPERCRONIC_{amd64,arm,arm64}_SHA1SUM`, and we need to evaluate this value as an env var. The easiest way to do this with `/bin/sh` seems to be `eval echo …
> adjust supercronic download to allow multiarch builds

- .circleci/config.yml
Confidence that this will work: 0% :)
I renamed the previous `build` job to `run_tests`, since it seemed more apt, if we're adding a "build the docker image" step. I think this requires a change on the github repo / PR config, though, so I'm fine reverting that change.
This PR hopefully adds the `build-and-publish-image` workflow, which waits for tests to run + waits for an approval from a maintainer / someone with merge access to the repo to run it. I think we need to create the `stringer-rss` Dockerhub user/organization, and we must use `DOCKER_LOGIN` and `DOCKER_PASSWORD` env vars but I'm not sure where to place them in the CI file in a safe way. (is this something we set up in CircleCI itself as a secret?)
> update circleci to build image and push to dockerhub, pending approval

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css
- app/commands/cast_boolean.rb
- app/controllers/passwords_controller.rb
- app/controllers/settings_controller.rb
- app/models/application_record.rb
- app/models/setting.rb
- app/models/setting/user_signup.rb
- app/views/layouts/_footer.html.erb
- app/views/sessions/new.erb
- app/views/settings/index.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20230721160939_create_settings.rb
- db/schema.rb
- spec/commands/cast_boolean_spec.rb
- spec/models/application_record_spec.rb
- spec/models/setting/user_signup_spec.rb
- spec/requests/debug_controller_spec.rb
- spec/requests/passwords_controller_spec.rb
- spec/requests/settings_controller_spec.rb
- spec/support/with_model.rb
- spec/system/account_setup_spec.rb
- spec/system/application_settings_spec.rb
**What**
This allows admins to enable and disable user signups in the app.
**Why**
This will help prevent bots from creating accounts if they manage to
find a stringer instance online, as well as allowing admins to control
who can create accounts. Fixes [#1063][is].
[is]: https://github.com/stringer-rss/stringer/issues/1063
> Add setting to control user signups

- Dockerfile
So all `RUN` commands will use the same shell.
> Docker: move `SHELL` line up

- .circleci/config.yml
This was only installing in the test container, not the Docker publish
container, which appears to already have it.
> Docker: remove docker install

- docker-compose.yml
Missing equal sign (=) in variable 'environment': ENCRYPTION_PRIMARY_KEY
> Fix typo in docker-compose

- .circleci/config.yml
- .github/workflows/build.yml
As mentioned in [#1051](https://github.com/stringer-rss/stringer/issues/1051#issuecomment-1679387966), the CircleCI docker build step isn't working, and we want to move it to a Github Action instead. This PR has two commits:
- first, revert the CircleCI additions so that the CircleCI tests file is clean (via reverting the two commits from #1065)
- second, add a build+push to dockerhub github action.
This will require two secrets that I *believe* can be set in the repository settings somewhere: one for a `DOCKERHUB_USERNAME` and another for a `DOCKERHUB_TOKEN`. I also went ahead and added both an amd64 and an arm64 build here, and am hoping that it just works (tm).
I also once again set the build and push to only happen when `main` is pushed to / gets new commits, but I think we can change …
> Build Docker image and push to Dockerhub

- Dockerfile
I was looking into how to pass the target arch into a build arg in the Dockerfile, when I found out that it's already available in `TARGETARCH`. So instead of using `ARCH` I renamed everything to `TARGETARCH` and got a successful amd64 build and arm64 build, with the correct versions of the supercronic binary attached. [Here's](https://github.com/guidopetri/stringer/actions/runs/5985463167/job/16237585875) the GH Actions logs; if you search for `supercronic` you can see L738/739 shows the amd64 build + output, and L1197/1198 shows the arm64 build + output.
> Use `TARGETARCH` to get supercronic binary per target platform

- docker/start.sh
I added an asset precompilation step to the Dockerfile. However, this didn't work out of the box - it seems like [rails needs secret keys/environment variables to be loaded](https://github.com/rails/rails/issues/32947) to run any command, even just an asset precompilation. So I added some dummy arguments to the Dockerfile that are only available during build, not during runtime. Unfortunately, this seems to be the standard: e.g. [Mastodon](https://github.com/mastodon/mastodon/blob/main/Dockerfile#L100) does this.
This wasn't quite satisfactory, so I went with another option: to precompile assets in `docker/start.sh`, i.e. the entrypoint of the container. This is also a little inconvenient, because if someone changes the entrypoint to the container, then they might not precompile the …
> precompile assets in the dockerfile before launching. closes #1086

- Dockerfile
Hey ! 
I found this [issue](https://github.com/stringer-rss/stringer/issues/1087) and I had time to answer it. So here is the PR. 
Today, this update install : 
- Nano v7.2
- Vim v9.0
Feel free to comment if I missed something
> Add Nano and Vim into Docker Image

- .dockerignore
The Docker image was building without copying the contents of `./tmp`, so the `/app/tmp/pids/.keep` folder didn't exist within the Docker container anymore. By removing this line from the `.dockerignore`, we create that folder and the image is back to working successfully.
I tested this on my local and the new image builds fine and loads stringer in the browser, (although we still have a missing assets issue).
> don't ignore existing tmp folder. closes #1096

- Dockerfile
Without setting this variable, Rails won't serve static files from within the Docker container while in production mode. We could circumvent this by having a shared volume to the assets folder and serving the assets through a reverse proxy, but it seems more trouble than it's worth at this point.
> set RAILS_SERVE_STATIC_FILES in the docker container

- spec/commands/feed/create_spec.rb
- spec/commands/feed/export_to_opml_spec.rb
Updated spec files below to address "MultipleMemoizedHelpers" cop
- spec/feeds/create_spec.rb
- spec/feeds/export_to_opml_spec.rb
> Removed memoization from feed/create and feed/export_to_opml specs

- spec/commands/feed/fetch_one_spec.rb
This moves stubbing in `feed/fetch_one_spec` from the `before` block
down to the `it` blocks where they are needed. This makes it more clear
where exactly they are used will allow us to refactor the tests
individually.
> Rubocop: reduce before block in feed/fetch_one_spec

- .circleci/config.yml
**What**
This introduces a new `repeat` workflow that will re-run a build every
20 minutes if the branch name includes `ci-repeat`. This will help us to
discover and address test flake.
> CircleCI: add repeat workflow

- Gemfile
- Gemfile.lock
- spec/support/axe_core.rb
**What**
This adds the `axe-core-rspec` gem and overrides the Capybara methods
`visit` and `click_on` to run accessibility checks after each click or
visit.
**Notes**
This doesn't currently have any affordances to reduce test flake. `axe`
is likely to end up running on partially loaded pages which could lead
to unexpected test failures. I'm planning on running the build on repeat
and fixing the errors as they come up.
I might also add some sort of "expect_text" parameter to require *all*
calls to expect some sort of text on the resulting page. I'm hesitant to
vary too far from the Capbyara API, though.
> A11y: add accessibility overrides for system tests

- spec/support/downloads.rb
- spec/system/export_spec.rb
Use Capybara's built-in `synchronize` method rather than handling the
timeout ourselves.
> update Downloads helpers to use synchronize

- .github/workflows/build.yml
This updates our Docker build configuration to also run on pull request,
as well as allowing for on-demand builds with the `workflow_dispatch`
option.
> Docker: run Docker buildx on PR and manually

- spec/repositories/feed_repository_spec.rb
- spec/repositories/story_repository_spec.rb
Removed "let" and "before" from FeedRepository spec and StoryRepository spec
Files modified:
spec/repositories/feed_repository_spec.rb
spec/repositories/story_repository_spec.rb
> refactor: removed memoization from repository spec

- spec/commands/feed/import_from_opml_spec.rb
- spec/commands/fever_api/read_favicons_spec.rb
- spec/commands/fever_api/write_mark_feed_spec.rb
- spec/commands/story/mark_as_read_spec.rb
Completed removal of remaining memoization across specs in commands folder.
Modified specs:
-  spec/commands/feed/import_from_opml_spec.rb
-  spec/commands/fever_api/read_favicons_spec.rb
-  spec/commands/fever_api/write_mark_feed_spec.rb
-  spec/commands/story/mark_as_read_spec.rb
> refactor: Removed Memoization From Commands Specs

- .circleci/config.yml
This should reduce the cache size for bundled gems.
> CircleCI: clean up bundled gems before caching

- app/commands/fever_api/read_items.rb
- spec/commands/fever_api/read_items_spec.rb
This will make it so that they are returned in a stable order.
> Update ReadItems to order stories by published and id

- db/migrate/20240226201050_add_precision_to_timestamps.rb
- db/schema.rb
Generate migration file to set the default precision to 6 for datetime columns in the database
> FIX: Add default precision to db

- .rubocop_todo.yml
- spec/helpers/url_helpers_spec.rb
- spec/integration/feed_importing_spec.rb
- spec/models/story_spec.rb
- spec/requests/feeds_controller_spec.rb
- spec/requests/imports_controller_spec.rb
Removed Memoization (let, before, etc.) from specs:
- spec/helpers/url_helpers.rb
- spec/integrations/feed_importing_spec.rb
- spec/models/story_spec.rb
- spec/requests/feeds_controller_spec.rb
- spec/requests/imports_controller_spec.rb
> Refactor: Remove memoization from spec test

- app/helpers/url_helpers.rb
turns out this wasn't necessary
> Rails8: remove URI.parse

- config/environments/production.rb
It causes an error because we're not passing a string.
> Rails8: don't pass base to Integer

- app/commands/feed/import_from_opml.rb
- app/utils/opml_parser.rb
- spec/commands/feed/import_from_opml_spec.rb
- spec/support/files/subscriptions.xml
While testing stringer locally, I tried to import my feeds from The Old Reader. The OPML generated by The Old Reader doesn't contain the feed names, so the import failed.
I made a change to allow nils and the import went through, but then the feeds had no name and it was hard to manage the feeds.
So I replicated the logic from `Feed::Create` to try to get a proper title for the Feed.
This will make the import slower in the case there's nameless entries, but the result seems to be better. I'm falling back to the url if the call to the feed failed to avoid retrying on dead feeds.
> Allow empty name during import and use FeedDiscovery to try to figure the name out if possible

- .github/workflows/build.yml
This switches to `ubuntu-22.04` and reenables arm64 builds. It turns out
there's [an issue with the Github Actions runner image][is]. People seem
to be having luck downgrading the image.
[is]: https://github.com/actions/runner-images/issues/11471
> Docker: re-enable arm64 builds

- config/locales/zh-TW.yml
Just update and improve the zh-TW Traditional Chinese locale.
Summary generated by GitHub Copilot:
> This pull request includes several updates to the Traditional Chinese (zh-TW) localization file. The changes focus on improving the consistency and formality of the language used throughout the application.
> 
> Key updates include:
> 
> ### Language Consistency and Formality:
> 
> * Updated various phrases to use more formal language, replacing informal pronouns and expressions with their formal counterparts.
> * Changed month names to use numeric representations with a space and the character "月" for clarity.
> 
> ### Terminology Standardization:
> 
> * Standardized the term "RSS" across different contexts, replacing inconsistent terms like "訊息來源" with "RSS".
> * Updated action labels …
> Update and improve zh-TW Traditional Chinese locale

- docker-compose.yml
This fixes https://github.com/stringer-rss/stringer/issues/1295.
> Add missing .env bind in example docker-compose.yml
