stringer-rss/stringer

- .rubocop_todo.yml
- Rakefile
- app/fever_api/authentication.rb
- app/models/story.rb
- app/repositories/feed_repository.rb
- app/repositories/story_repository.rb
- app/tasks/change_password.rb
- app/tasks/fetch_feed.rb
- app/utils/feed_discovery.rb
- app/utils/sample_story.rb
- config/unicorn.rb
- spec/repositories/feed_repository_spec.rb
- spec/support/active_record.rb
- spec/support/feed_server.rb
~~There's currently one rule left, `Lint/RescueException`, that needs more thought.~~
Ready for review.
> Fix RuboCop lint offences

- docs/VPS.md
Add nginx configuration sample form issue#413 and more tips for SSL/TLS
> Add nginx config sample to docs/VPS.md

- Dockerfile
- README.md
- docker/start.sh
- docker/supervisord.conf
- docs/docker.md
This PR adds a Dockerfile so Stringer can easily be ran in Docker.
For convenience there's a single container running both Unicorn as well
as cronjobs.
This goes a little against the Docker mantra of running only a single
process per container, but hey :-)
> Add Dockerfile

- docs/VPS.md
Hello, I had a hard time deploying stringer.
After I tested out and make it running on my VPS, I decided to document it for other stringer users.
Please review my PR, thanks.
FYI, related issue:
#189 Deploy with Passenger + Apache
#421 "autostarting" stringer on distros with systemd
> Docs VPS.md fullfill - systemd and mod_passenger

- app/models/user.rb
- spec/factories/users.rb
- spec/repositories/user_repository_spec.rb
- spec/spec_helper.rb
Also:
* Add factory helpers for `User` records
* Remove method `User#setup_complete?`. ActiveRecord automatically
provides predicate (`?`) methods for model attributes, so it's not
necessary.
> Specs: add tests for UserRepository

- spec/factories/feeds.rb
- spec/factories/stories.rb
- spec/models/group_spec.rb
- spec/models/story_spec.rb
- spec/spec_helper.rb
As well as factory helpers for `feeds` and `stories`.
> Specs: add specs for Group and Story

- spec/models/story_spec.rb
The date seems to be coming back in UTC.
> Specs: fix flaky story_spec

- config/asset_pipeline.rb
- spec/config/asset_pipeline_spec.rb
I enabled settings for test mode, which doesn't seem to noticeably
impact performance, but gives us a little bit more test coverage.
> Specs: add tests for asset_pipeline.rb

- spec/factories/stories.rb
- spec/repositories/story_repository_spec.rb
- spec/support/coverage.rb
This brings test coverage up to 100%, so I'm also enabling the
`minimum_coverage` threshold to make sure it stays there.
> Specs: add more tests for StoryRepository

- Gemfile.lock
There doesn't appear to be anything in [the major release][release] that
should impact us.
[release]: https://github.com/defunkt/unicorn/releases/tag/v6.0.0
> Deps: upgrade Unicorn to 6.0.0

- config/locales/zh-TW.yml
> Add Traditional Chinese (zh-TW) locale

- app/assets/stylesheets/application.css
This PR extracted the changes to the stylesheet from #488.
I tried it locally and it looks good enough for a first release. Maybe we can fine tune things later if we want.
closes #464
> Add support for mobile screen sizes

- app/tasks/fetch_feed.rb
Logging feed errors should be helpful for debugging.
> Set a logger inside FetchFeed

- Gemfile
Put common gems ahead of environment based ones.
> Rearrange gemfile

- .rubocop.yml
- app/controllers/application_controller.rb
- spec/controllers/debug_controller_spec.rb
- spec/controllers/feeds_controller_spec.rb
We'll be needing a bit more robust flash support in subsequent changes.
> Rails: use Sinatra hash in controller

- .rubocop.yml
- .rubocop_todo.yml
- app/helpers/authentication_helpers.rb
- app/helpers/url_helpers.rb
- config/asset_pipeline.rb
- spec/controllers/stories_controller_spec.rb
- spec/fever_api/read_items_spec.rb
- spec/helpers/authentications_helper_spec.rb
- spec/helpers/url_helpers_spec.rb
- spec/javascript/test_controller.rb
Sticking with brackets for consistency.
> RuboCop: switch WordArray rule

- .rubocop.yml
- spec/app_spec.rb
- spec/config/asset_pipeline_spec.rb
- spec/controllers/debug_controller_spec.rb
- spec/controllers/exports_controller_spec.rb
- spec/controllers/feeds_controller_spec.rb
- spec/controllers/imports_controller_spec.rb
- spec/controllers/passwords_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/controllers/stories_controller_spec.rb
- spec/controllers/tutorials_controller_spec.rb
- spec/spec_helper.rb
- spec/support/controller_helpers.rb
- spec/utils/i18n_support_spec.rb
I want to make the tests look more like Rails controller tests, so we
can add custom methods here.
> Rails: add ControllerHelpers in tests

- app/assets/javascripts/application.js
- app/controllers/feeds_controller.rb
- app/views/feeds/_feed.html.erb
- config/locales/de.yml
- config/locales/el-GR.yml
- config/locales/en.yml
- config/locales/eo.yml
- config/locales/es.yml
- config/locales/fr.yml
- config/locales/he.yml
- config/locales/it.yml
- config/locales/ja.yml
- config/locales/nl.yml
- config/locales/pt-BR.yml
- config/locales/pt.yml
- config/locales/ru.yml
- config/locales/sv.yml
- config/locales/tr.yml
- config/locales/zh-CN.yml
- config/locales/zh-TW.yml
This ensures that the authenticity token will be generated and submitted
when deleting a feed.
> Rails: use button_to for deleting feed

- config/initializers/session_store.rb
Fixes: https://github.com/stringer-rss/stringer/issues/690
> Rails: add 2 week session expiration

- .env.development
- .env.test
- Gemfile
- Gemfile.lock
- app.json
- config/initializers/dotenv.rb
- docker-compose.yml
- docs/Heroku.md
- docs/OpenShift.md
- docs/VPS.md
- docs/docker.md
This adds a requirement for `SECRET_KEY_BASE` to ensure that it's set
before running the app.
> Rails: set up dotenv-rails

- .env.development
- .env.test
- app.json
- app/models/user.rb
- config/application.rb
- config/initializers/dotenv.rb
- db/migrate/20230301024452_encrypt_api_key.rb
- db/schema.rb
- docker-compose.yml
- docs/Heroku.md
- docs/OpenShift.md
- docs/VPS.md
- docs/docker.md
This will make it so that we can safely look up the user by API key
without the risk of timing attacks.
> MultiUsers: encrypt API key

- config/database.yml
This wasn't working for me locally without the `host` option.
> Add host to database.yml

- spec/commands/feed/fetch_one_spec.rb
- spec/support/generate_xml.rb
Introduce new xml generator and use that rather than stubbing private
method
> Update Fetch One spec

- app/views/layouts/application.html.erb
- spec/javascript/support/views/test/index.html.erb
- spec/support/axe_core.rb
Co-authored-by: Rob Young <rhyoung214@gmail.com>
> A11y: fix html-has-lang accessibility violations

- app/views/imports/new.html.erb
- spec/support/axe_core.rb
Co-authored-by: Rob Young <rhyoung214@gmail.com>
> A11y: fix violation of label-title-only rule

- docker-compose.yml
- docs/Docker.md
Hey ! 
As mentionned [here](https://github.com/stringer-rss/stringer/pull/1071/files), I splitted my first PR into small one. As we can merge it easily !
In this one : 
- Sync Pg volume between documentation and docker-compose
- Upgrade to Postgres 12
Feel free to comment if I missed something
> Relocate Postgres Database and Upgrade to Postgres 12

- db/schema.rb
This updates the schema format with the latest defaults.
> Rails7.1: update schema format

- app/commands/fever_api/read_feeds_groups.rb
- app/commands/fever_api/read_groups.rb
- app/commands/fever_api/read_items.rb
- app/models/group.rb
- spec/commands/fever_api/read_groups_spec.rb
- spec/commands/fever_api/read_items_spec.rb
- spec/requests/fever_controller_spec.rb
Make the Fever API compatible with [Read You](https://github.com/Ashinch/ReadYou)
See the full commit messages for more reasoning.
> Fever API: Read You compatibility

- db/migrate/20230223045525_add_null_false_to_associations.rb
- db/migrate/20230223231930_add_username_to_users.rb
- db/migrate/20230301024452_encrypt_api_key.rb
- db/migrate/20230313034938_add_admin_to_users.rb
Fixes https://github.com/stringer-rss/stringer/issues/1183.
> Refactor migrations to not use ActiveRecord for compatibility

- app/views/feeds/new.html.erb
it was just the missing class :)
> fix #1213 adding a class
